name: Azure Static Web Apps CI/CD - Zarcillo

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Zarcillo

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0A05E910F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "out"
          app_build_command: "npm run build"
        env:
          IS_STATIC_EXPORT: true
          NEXT_PUBLIC_SUPABASE_URL: https://vndxwvmrsymxprgwhsup.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuZHh3dm1yc3lteHByZ3doc3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1NzkyMjEsImV4cCI6MjA5NTE1NTIyMX0.KW2Epmh055-ILFBWUB7lT6x4sIZSIjtY63yelIsSZfE
          NEXT_PUBLIC_LAMP_COMMAND_ENDPOINT: https://team-limbert-gabriel-limberttt-975f8e81.flowfuse.cloud/lamp

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_0A05E910F }}
          action: "close"